### ISSUE TITLE
Writing directly to pack buffer

### ISSUE THREAD

**Issue by olofk** [clwi/CWPack#1]
Hi,

I'm using cwpack to send large binary objects together with some metadata. As the binary objects are quite large I would like to avoid an unnecessary memcpy. Is there a way to just reserve space when packing and then get a pointer that I can pass to my data producer to have it write into the pack buffer directly?

**Comment by clwi** [comment]
Hej

This is simple if you know the size of the blob before you output it. Just

#include "cwpack_defines.h"

void prepare_pack_bin(cw_pack_context* pack_context, uint32_t length, uint8_t **pointer)
{
    *pointer = NULL;

    if (pack_context->return_code)
        return;
    
    uint8_t *p;
    
    if (l < 256)            // Bin 8
    {
        cw_pack_reserve_space(l+2);
        *p++ = (uint8_t)(0xc4);
        *p = (uint8_t)(l);
        *pointer = p+1;
        return;
    }
    if (l < 65536)     // Bin 16
    {
        cw_pack_reserve_space(l+3)
        *p++ = (uint8_t)0xc5;
        cw_store16(l);
        *pointer = p+2;
        return;
    }
    // Bin 32
    cw_pack_reserve_space(l+5)
    *p++ = (uint8_t)0xc6;
    cw_store32(l);
    *pointer = p+4;
    return;
}


As you can see,  this routine outputs the correct opcode and length and then the pointer to the pack buffer is returned in *pointer.

Disclaimer: I haven´t tested the routine above.

OT: Are you also Swedish?

/Claes

**Comment by olofk** [comment]
Thanks for the quick reply. Yes, the blob size is known in my case. I'll try it today or tomorrow. Took a while to figure out how this would work until I realized that cw_pack_reserve_space and cw_store are defines instead of functions. Sneaky! :)

I'll close the issue when I have tested it.

OT: Yes I am. From the frontside of Sweden

**Comment by clwi** [comment]
Sorry, I just wrote l instead of length in the code snippet. It should be:

#include "cwpack_defines.h"

void prepare_pack_bin(cw_pack_context* pack_context, uint32_t length, uint8_t **pointer)
{
    *pointer = NULL;

    if (pack_context->return_code)
        return;

    uint8_t *p;

    if (l < 256)            // Bin 8
    {
        cw_pack_reserve_space(length +2);
        *p++ = (uint8_t)(0xc4);
        *p = (uint8_t)(length);
        *pointer = p+1;
        return;
    }
    if (l < 65536)     // Bin 16
    {
        cw_pack_reserve_space(length +3)
        *p++ = (uint8_t)0xc5;
        cw_store16(length);
        *pointer = p+2;
        return;
    }
    // Bin 32
    cw_pack_reserve_space(length+5)
    *p++ = (uint8_t)0xc6;
    cw_store32(length);
    *pointer = p+4;
    return;
}

/Claes

**Comment by olofk** [comment]
This works fine. Thanks for the help
