### ISSUE TITLE
Example is not working!

### ISSUE THREAD

**Issue by crono2250** [clwi/CWPack#14]
The example described in readme.md does not seem to work with the latest version.
Specifically, the following two functions do not seem to exist in the source of the master branch.

cw_unpack_next_map_size()
cw_unpack_next_str_length()

**Comment by clwi** [comment]
The example is not a whole working program. It is using the expect api that is defined in goodies/utils. Insert utils.h and it will compile.

**Comment by crono2250** [comment]
Thank you for your information. thanks!
