### ISSUE TITLE
Unaligned access with 64-bit data on M4

### ISSUE THREAD

**Issue by dRomke** [clwi/CWPack#6]
On ARM Cortex-M4 (STM32F439) I get a hard fault error when CWPack tries to do unaligned access to 64-bit data. M4 does support unaligned access, but only on <=32-bit data (being a 32-bit microcontroller).

The hard fault happens on `tmpu64 = *(uint64_t*)ptr;` (in [cwpack_defines.h](https://github.com/clwi/CWPack/blob/master/src/cwpack_defines.h)) when ptr is anything but a multiple of 4. `tmpu32` and `tmpu16` are perfectly fine with unaligned access, `tmpu64` is not.
Replacing `*(uint64_t*)ptr` with `(uint64_t)(*(uint32_t*)(ptr+4)) << 32u | *(uint32_t*)ptr` fixes this problem, but I admit it can be done cleaner.

What are your thoughts on this?

Btw. Enabling FORCE_ALIGNMENT does also solve the issue, but then I do not get all the benefits of fast execution on 32 or 16 bit (most used).

Thanks for this nice little piece of code 🙂.

**Comment by clwi** [comment]
Thank you for pinpointing this problem. I will introduce FORCE_ALIGNMENT_64BIT to solve this problem. The next release is just some days away now.

**Comment by clwi** [comment]
FORCE_ALIGNMENT_64BIT is included in release 1.2

**Comment by dRomke** [comment]
Hi,
Thanks for the quick response & fix. I haven't had time to check this one out yet, will do this tomorrow.

Btw. am I right in assuming this library isn't targeted at embedded platforms? Integers for example are also default 64 bit (64 bit takes at least 2 instructions, and who needs 64 bit integers anyway...). But these are just my thoughts.
